from django.contrib import admin
from models import *

admin.site.register(User)
admin.site.register(Resource)
admin.site.register(Tag)
admin.site.register(Feature)
admin.site.register(Size)
admin.site.register(BackupWindow)
admin.site.register(Region)
admin.site.register(Action)
admin.site.register(Domain)
admin.site.register(DomainRecord)
admin.site.register(Network)
admin.site.register(Kernel)
admin.site.register(SSHKey)
admin.site.register(Image)
admin.site.register(Storage)
admin.site.register(Container)
admin.site.register(FloatingIP)
