# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 09:22
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('container_limit', models.IntegerField(default=10, help_text='The total number of containers the user may have', verbose_name='Container Limit')),
                ('floating_ip_limit', models.IntegerField(default=3, help_text='The total number of floating IPs the user may have', verbose_name='Floating IP Limit')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(help_text='The current status of the action.', verbose_name='Status')),
                ('type', models.CharField(help_text='This is the type of action that the object represents. For example, this could be "transfer" to represent the state of an image transfer action.', max_length=20, verbose_name='Type')),
                ('started_at', models.DateTimeField(help_text='A time value given in ISO8601 combined date and time format that represents when the action was initiated.', verbose_name='Started At')),
                ('completed_at', models.DateTimeField(help_text='A time value given in ISO8601 combined date and time format that represents when the action was completed.', verbose_name='Completed At')),
            ],
        ),
        migrations.CreateModel(
            name='BackupWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='A time value given in ISO8601 combined date and time format that represents when the backup will start.', verbose_name='Start')),
                ('end', models.DateTimeField(help_text='A time value given in ISO8601 combined date and time format that represents when the backup will end.', verbose_name='End')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The human-readable name set for the Container instance.', max_length=60, verbose_name='Name')),
                ('memory', models.IntegerField(help_text='Memory of the Container in megabytes.', verbose_name='Memory')),
                ('vcpus', models.IntegerField(help_text='The number of virtual CPUs.', verbose_name='CPUs')),
                ('disk', models.IntegerField(help_text="The size of the Container's disk in gigabytes.", verbose_name='Disk')),
                ('locked', models.BooleanField(help_text='A boolean value indicating whether the Container has been locked, preventing actions by users.', verbose_name='Locked')),
                ('created_at', models.DateTimeField(help_text='A time value given in ISO8601 combined date and time format that represents when the Container was created.', verbose_name='Created At')),
                ('status', models.IntegerField(choices=[(0, b'new'), (1, b'active'), (2, b'off'), (3, b'archive')], help_text='A status string indicating the state of the Droplet instance. This may be "new", "active", "off", or "archive".', verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the domain itself. This should follow the standard domain format of domain.TLD. For instance, example.com is a valid domain name.', max_length=60, verbose_name='Name')),
                ('ttl', models.IntegerField(help_text='This value is the time to live for the records on this domain, in seconds. This defines the time frame that clients can cache queried information before a refresh should be requested.', verbose_name='TTL')),
                ('zone_file', models.TextField(help_text='This attribute contains the complete contents of the zone file for the selected domain. Individual domain record resources should be used to get more granular control over records. However, this attribute can also be used to get information about the SOA record, which is created automatically and is not accessible as an individual record resource.', verbose_name='Zone File')),
            ],
        ),
        migrations.CreateModel(
            name='DomainRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name to use for the DNS record.', max_length=60, verbose_name='Name')),
                ('type', models.IntegerField(choices=[(0, b'A'), (1, b'AAAA'), (2, b'CNAME'), (3, b'MX'), (4, b'TXT'), (5, b'SRV'), (6, b'NS')], help_text='The type of the DNS record (ex: A, CNAME, TXT, ...).', verbose_name='Type')),
                ('data', models.CharField(help_text='The value to use for the DNS record.', max_length=60, verbose_name='Value')),
                ('priority', models.IntegerField(help_text='The priority for SRV and MX records.', null=True, verbose_name='Priority')),
                ('port', models.IntegerField(help_text='The port for SRV records.', null=True, verbose_name='Port')),
                ('weight', models.IntegerField(help_text='The weight for SRV records.', null=True, verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(help_text='A feature (f.e. if a Container can be backed up)', max_length=20, verbose_name='Feature')),
            ],
        ),
        migrations.CreateModel(
            name='FloatingIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='The public IP address of the Floating IP. It also serves as its identifier.', max_length=45, verbose_name='IP')),
                ('container', models.ForeignKey(help_text='The Container that the Floating IP has been assigned to.', on_delete=django.db.models.deletion.CASCADE, to='api.Container', verbose_name='Container')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name that has been given to an image. This is what is shown in the control panel and is generally a descriptive title for the image in question.', max_length=60, verbose_name='Name')),
                ('type', models.IntegerField(choices=[(0, b'snapshot'), (1, b'backup')], help_text='The kind of image, describing the duration of how long the image is stored. This is either "snapshot" or "backup".', verbose_name='Type')),
                ('distribution', models.CharField(help_text='This attribute describes the base distribution used for this image.', max_length=100, verbose_name='Distribution')),
                ('slug', models.CharField(help_text='A uniquely identifying string that is associated with each of the provided public images. These can be used to reference a public image as an alternative to the numeric id.', max_length=100, verbose_name='Slug')),
                ('public', models.BooleanField(help_text='This is a boolean value that indicates whether the image in question is public or not. An image that is public is available to all accounts. A non-public image is only accessible from your account.', verbose_name='Public')),
                ('min_disk_size', models.IntegerField(help_text="The minimum 'disk' required for a size to use this image.", verbose_name='Minimum Disk Size')),
                ('size_gigabytes', models.IntegerField(help_text='The size of the image in gigabytes.', verbose_name='Size')),
                ('created_at', models.DateTimeField(help_text='A time value given in ISO8601 combined date and time format that represents when the Image was created.', verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the kernel.', max_length=100, verbose_name='Name')),
                ('version', models.CharField(help_text='The version of the kernel.', max_length=100, verbose_name='Version')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(choices=[(0, b'v4'), (1, b'v6')], help_text='The version of the network (can be v4 or v6)', verbose_name='Version')),
                ('netmask', models.CharField(help_text='The netmask of the network.', max_length=45, verbose_name='Netmaks')),
                ('gateway', models.CharField(help_text='The gateway of the network.', max_length=45, verbose_name='Gateway')),
                ('type', models.IntegerField(choices=[(0, b'public'), (1, b'private')], help_text='The type of the network (can be public or private)', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the region. This will be a full name that is used in the control panel and other interfaces.', max_length=20, verbose_name='Name')),
                ('slug', models.CharField(help_text='A human-readable string that is used as a unique identifier for each region.', max_length=4, verbose_name='Slug')),
                ('available', models.BooleanField(help_text='This is a boolean value that represents whether new Containers can be created in this region.', verbose_name='Available')),
                ('features', models.ManyToManyField(help_text='The features available in this region.', to='api.Feature', verbose_name='Features')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(help_text='The key (id) of the resource.', verbose_name='Key')),
                ('value', models.CharField(help_text='The value for the resource (f.e. the type of the resource)', max_length=80, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='A human-readable string that is used to uniquely identify each size.', max_length=10, verbose_name='Slug')),
                ('available', models.BooleanField(help_text='This is a boolean value that represents whether new Containers can be created with this size.', verbose_name='Available')),
                ('transfer', models.DecimalField(decimal_places=1, help_text='The amount of transfer bandwidth that is available for Containers created in this size. This only counts traffic on the public interface. The value is given in terabytes.', max_digits=6, verbose_name='Bandwith')),
                ('price_monthly', models.DecimalField(decimal_places=1, help_text='This attribute describes the monthly cost of this Container size if the Container is kept for an entire month.', max_digits=5, verbose_name='Price Monthly')),
                ('price_hourly', models.DecimalField(decimal_places=1, help_text='This describes the price of the Container size as measured hourly.', max_digits=8, verbose_name='Price Hourly')),
                ('memory', models.IntegerField(help_text='The amount of RAM allocated to Containers created of this size. The value is represented in megabytes.', verbose_name='Memory')),
                ('vcpus', models.IntegerField(help_text='The number of virtual CPUs allocated to Containers of this size.', verbose_name='CPUs')),
                ('disk', models.IntegerField(help_text='The amount of disk space set aside for Containers of this size. The value is represented in gigabytes.', verbose_name='Disk')),
            ],
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This is the human-readable display name for the given SSH key. This is used to easily identify the SSH keys when they are displayed.', max_length=60, verbose_name='Name')),
                ('fingerprint', models.CharField(help_text='This attribute contains the fingerprint value that is generated from the public key. This is a unique identifier that will differentiate it from other keys using a format that SSH recognizes.', max_length=512, verbose_name='Fingerprint')),
                ('public_key', models.TextField(help_text="This attribute contains the entire public key string that was uploaded. This is what is embedded into the root user's authorized_keys file if you choose to include this SSH key during Container creation.", verbose_name='Public Key')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A human-readable name for the Storage volume. Must be lowercase and be composed only of numbers, letters and "-", up to a limit of 64 characters.', max_length=64, verbose_name='Name')),
                ('description', models.CharField(help_text='An optional free-form text field to describe a Storage volume.', max_length=120, verbose_name='Description')),
                ('size_gigabytes', models.IntegerField(help_text='The size of the Storage volume in GiB (1024^3).', verbose_name='Size')),
                ('created_at', models.DateTimeField(help_text='A time value given in ISO8601 combined date and time format that represents when the Storage volume was created.', verbose_name='Created At')),
                ('containers', models.ForeignKey(help_text='The Containers the volume is attached to.', on_delete=django.db.models.deletion.CASCADE, to='api.Container', verbose_name='Containers')),
                ('region', models.ForeignKey(help_text='The region that the Storage volume is located in.', on_delete=django.db.models.deletion.CASCADE, to='api.Region', verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the tag. The supported characters for names include alphanumeric characters, dashes, and underscores.', max_length=80, verbose_name='Name')),
                ('resources', models.ManyToManyField(help_text='The resource associated with this tag.', to='api.Resource', verbose_name='Resources')),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='sizes',
            field=models.ManyToManyField(help_text='The sizes available in this region.', to='api.Size', verbose_name='Sizes'),
        ),
        migrations.AddField(
            model_name='image',
            name='regions',
            field=models.ManyToManyField(help_text='This attribute is an array of the regions that the image is available in.', to='api.Region', verbose_name='Regions'),
        ),
        migrations.AddField(
            model_name='floatingip',
            name='region',
            field=models.ForeignKey(help_text='The region that the Floating IP is reserved to. When you query a Floating IP, the entire region object will be returned.', on_delete=django.db.models.deletion.CASCADE, to='api.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='container',
            name='base_image',
            field=models.ForeignKey(help_text='The base image used to create the Container instance.', on_delete=django.db.models.deletion.CASCADE, related_name='base_image', to='api.Image', verbose_name='Base Image'),
        ),
        migrations.AddField(
            model_name='container',
            name='features',
            field=models.ForeignKey(help_text='A collection of features enabled on this Container.', on_delete=django.db.models.deletion.CASCADE, to='api.Feature', verbose_name='Features'),
        ),
        migrations.AddField(
            model_name='container',
            name='images',
            field=models.ManyToManyField(help_text='A collection of the backups and shapshots associated with this Container.', related_name='images', to='api.Image', verbose_name='Images'),
        ),
        migrations.AddField(
            model_name='container',
            name='kernel',
            field=models.ForeignKey(help_text='The current kernel. This will initially be set to the kernel of the base image when the Container is created.', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Kernel', verbose_name='Kernel'),
        ),
        migrations.AddField(
            model_name='container',
            name='networks',
            field=models.ManyToManyField(help_text='The details of the network that are configured for the Container instance.', to='api.Network', verbose_name='Networks'),
        ),
        migrations.AddField(
            model_name='container',
            name='next_backup_window',
            field=models.OneToOneField(help_text="The details of the Container's backups feature, if backups are configured for the Container.", null=True, on_delete=django.db.models.deletion.CASCADE, to='api.BackupWindow', verbose_name='Next Backup Window'),
        ),
        migrations.AddField(
            model_name='container',
            name='region',
            field=models.ForeignKey(help_text='The region that the Container instance is deployed in.', on_delete=django.db.models.deletion.CASCADE, to='api.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='container',
            name='size',
            field=models.ForeignKey(help_text='The current size object describing the Container.', on_delete=django.db.models.deletion.CASCADE, to='api.Size', verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='container',
            name='tags',
            field=models.ManyToManyField(help_text='A collection of Tags the Container has been tagged with.', to='api.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='container',
            name='volumes',
            field=models.ManyToManyField(help_text='A collection containing each Storage volume attached to the Container.', to='api.Storage', verbose_name='Volumes'),
        ),
        migrations.AddField(
            model_name='action',
            name='region',
            field=models.ForeignKey(help_text='The region where the action occurred.', on_delete=django.db.models.deletion.CASCADE, to='api.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='action',
            name='resource',
            field=models.OneToOneField(help_text='The resource that the action is associated with.', on_delete=django.db.models.deletion.CASCADE, to='api.Resource', verbose_name='Resource'),
        ),
    ]
